### ISSUE TITLE
Is Contributions Welcome?

### ISSUE THREAD

**Issue by loneicewolf** [lukasbalazik123/1337kit#2]
Hello!
Nice repo! I wanted to ask if contributions is welcome? Because I do not see a `CONTRIB` file.

Wishes!

**Comment by loneicewolf** [comment]
Why I ask is because I was going to try to help out with the Cryptography part; namely:
- [ ] `AES Encryption support`

![image](https://github.com/lukasbalazik/1337kit/assets/68499986/bbe905e5-4423-495a-b636-9b1c3e30ad27)

**Comment by loneicewolf** [comment]
I don't know if a mention is uh  needed (I am still a bit unsure how GitHubs comms system work) @lukasbalazik  <- sorry for the ping/mention!  Just so this question is seen;  if you dont have time to answer it's totally fine! ^_^ 

Regards!

**Comment by loneicewolf** [comment]
Closing it, feel free to re-open it if needed.

**Comment by lukasbalazik** [comment]
Hello!, im sorry i did not replied sooner, had a lot of work, rn i dont have much time to put any work into this project, but of course if you will do AES encryption support, i will gladly accept it into project

**Comment by loneicewolf** [comment]
Oh okay! and No worries, really  :)
